### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by yammadev** [goodheads/facebook-auth-laravel#1]
Hi there, nice repository. But I think that there are 3 bugs/errors (?) 

**1. Exception Error**
This is simple, if the user doesn't accept the app, then the app sends an error. It can be solved
replacing `Exception $e` for `\Exception $e`, or putting `Use Exception` at the beginning.

**2. Loop?**
I'm not sure, but If you put `return redirect('auth/facebook');` -which is the same authorization route- you will get a loop when the user rejects the app. It can be solved using something like:
```
return redirect('login')->with('status', 'You have rejected the facebook app');
```
and displaying the status properly in your login blade template.

**Comment by unicodeveloper** [comment]
Thanks @yammadev . A PR is welcome to fix the issue
